### ISSUE TITLE
Request for Android 6 Compatibility

### ISSUE THREAD

**Issue by ShareASmile** [jamal2362/URL-Radio#1]
It is heartening to know that a fork of Transistor app , URL-Radio  is being worked upon.

I would Request Lowering App's Minimum Sdk Requirement to 23. It would be very useful to many users like me who are stuck on Android 6 & can't upgrade due to various reasons.

Thank You & Cheers for this Wonderful Open Source Project.

**Comment by Go-rom** [comment]
Hi,

for what it's worth, i'm using an android 6 device as a dedicated webradio player.

It runs RadioDroid, it's less user friendly than URL-Radio/Transistor but it works great and it provides a search feature. It's available on F-Droid store.

Also, Transistor dev has left a repository with an older version of Transistor, called Transistor one.
But you have to know that there is no search feature, you have to manually add URLs.
https://github.com/y20k/transistorone

Hope it will help !

**Comment by shom13** [comment]
I agree with @ShareASmile that lowering of sdk support would be really useful, as i use my older device to stream radio. Please do consider supporting older devices.

**Comment by jamal2362** [comment]
I will see if this is possible. But I can not promise anything.

**Comment by jamal2362** [comment]
@ShareASmile and @shom13

I have made small changes so that this also works with the SDK/API 23. So Android 6.0.
Please test this APK, if everything is ok then I will make the changes.
It is important that this is tested on an Android 6.0 device.

https://we.tl/t-PJmsobZrvg

**Comment by shom13** [comment]
I checked on android 7, and i can confirm it works. Unfortunately i dont have an android 6 device. But i have 5.1 device and as expected it wont install.

**Comment by ShareASmile** [comment]
Thank you for the effort to support Android 6. I have tested above test apk a bit on Samsung SM-J210F aka J2Pro 2016 on android 6
First Impression:-

App is Lite to use
Starts Playing Radio Stations Instantly on Stable LTE Internet Connection
So for it is working well & not too heavy on 2GB RAM Low spec phone, though when adding new Radio Station if search results return more than 40-50 entries then scrolling in stations List to add station is not smooth, stucks a bit though not a big deal.

Testing:-
1) Adding stations:- Works
2) Station Playback: Works Beautifully
3) Export m3u Station List: Works on to both Internal Memory & External Storage.
5) I haven't found any problem in Dark or Light Theme as well.
And It Is Stable enough to be included in development.

**Comment by jamal2362** [comment]
@ShareASmile 
Thank you for testing.

@shom13 
I have made changes to get the Radio working for devices with Android 5.0 and up.
Please test this APK and give me a feedback.

https://we.tl/t-MQtRjsruqA

**Comment by shom13** [comment]
Tested on android 5.1. I was able to install, and add stations as expected. Did not notice anything problematic during playback. Its running smoothly. I was also able to export added channels as backup. So overall looks perfectly functional. I will still be using the app more and report back if i notice anything unexpected.

**Comment by ShareASmile** [comment]
While Testing above URL_Radio_ 8.4-test-release observed improvement in performance over first test 8.3 apk on SM-j2210f  on android 6.0.1.

But Found one issue in both test apks while streaming m3u8 Stop button does not appear in Notification, can't dismiss Notification after quitting out of app neither by device back button nor by removing app from recent apps had to force stop app to close notification. This behaviour is only with streams ending with m3u8
Edit: Here is screeshot with m3u8 stream
![Screenshot_20220312-203838](https://user-images.githubusercontent.com/60492161/158025121-6c8b8517-e369-49cd-9170-182fdb0f5656.png)
Notification otherwise looks like this:-
![Screenshot_testUrlRadio_8 4](https://user-images.githubusercontent.com/60492161/158027758-55592287-5508-49b4-b756-95558db65ae4.jpg)
