### ISSUE TITLE
Suggestion: Drag & Drop/Custom Ordering 

### ISSUE THREAD

**Issue by ximcix** [jamal2362/URL-Radio#11]
Currently all stations are ordered by the date they were added, but I would like to order them as I see fit by sliding up or down, but I don't believe this or any other method of ordering stations is currently possible.

Best regards,
- mc -

**Comment by jamal2362** [comment]
This is not currently planned.
It is automatically sorted from 0-9 and A-Z.
If you want to have a radio station on top then set it to favorite by swiping this station.

**Comment by jamal2362** [comment]
This feature should now be built into the new URL Radio version.

Have fun. 😊

https://github.com/jamal2362/URL-Radio/commit/22e13903fb651515220bfefc827f4387854b9698
