### ISSUE TITLE
Cannot fetch stations art covers

### ISSUE THREAD

**Issue by serrq** [jamal2362/URL-Radio#14]
I don't get anything after push the proper button.

**Comment by bbbhltz** [comment]
I notice this too. It depends on if the stream has a favicon value on https://www.radio-browser.info/

**Comment by jamal2362** [comment]
I just compared the cover of radio-browser.info with that of the URL Radio app.
I could not find any bug here.

In radio-browser.info there is not a logo for each radio station, so URL Radio shows the default logo.

But you can set your own logo for a station, just long click the station.
Pictures must be in the "Pictures" folder in the internal memory.
