### ISSUE TITLE
Custom sleep time adding block

### ISSUE THREAD

**Issue by serrq** [jamal2362/URL-Radio#15]
I would set the the time block to 15 minutes.

**Comment by jamal2362** [comment]
As soon as you press the timer button, it will show you 5 minutes. If you want to increase it, you have to press the timer button again. The time will always increase by 5 minutes more.

**Comment by serrq** [comment]
> As soon as you press the timer button, it will show you 5 minutes. If you want to increase it, you have to press the timer button again. The time will always increase by 5 minutes more.

I mean to increase by 15 minutes at a time instead of 5 minutes: to get to 90 minutes of sleep timer I should hit the button 6 times, not 18.

**Comment by jamal2362** [comment]
I leave this at 5 minutes so you can vary it better. Some people only want to listen for 10, 20 or 25 minutes and that doesn't work when it's increased to 15 minutes.

**Comment by serrq** [comment]
> I leave this at 5 minutes so you can vary it better. Some people only want to listen for 10, 20 or 25 minutes and that doesn't work when it's increased to 15 minutes.

Couldn’t you make that value arbitrary?
