### ISSUE TITLE
Excessive battery drain

### ISSUE THREAD

**Issue by serrq** [jamal2362/URL-Radio#17]
![Screenshot_2022-12-18-20-36-04-48_0ba066473b79d6e213a1f6f52505e2ee (1)](https://user-images.githubusercontent.com/113377431/208316048-b40f0d39-e58b-4e37-8d9f-567c1f101c85.jpg)

![Screenshot_2022-12-18-20-36-40-05_0ba066473b79d6e213a1f6f52505e2ee (1)](https://user-images.githubusercontent.com/113377431/208316053-f4ce2307-c84b-4e77-8d60-d463f1c0960b.jpg)

Today I used the app ~50 minutes (in total) when I trained.
I also had Transistor that didn't consume very much.

**Comment by jamal2362** [comment]
How long did you have a total URL radio running time?

Unfortunately I can not see this exactly on the screenshot because I do not know the language.

**Comment by serrq** [comment]
> How long did you have a total URL radio running time?
> 
> Unfortunately I can not see this exactly on the screenshot because I do not know the language.

Which reminds me about an hour. 

Wait tomorrow and I’ll do a new measurement.

**Comment by jamal2362** [comment]
Ok 👍

As far as I can see, the app was running in the background for almost 9 hrs.

I think it was not closed completely.

**Comment by serrq** [comment]
![Screenshot_2022-12-20-14-47-33-52_73aa37116af19d51e8a8a618563a9143 (1)](https://user-images.githubusercontent.com/113377431/208682012-2e4b9b76-b813-4da1-b913-853911180e87.jpg)


Today I noticed a normal battery consumption, so I believe that I didn't shutdown properly the app.

Can you add "quit" button in the bottom? (see the red line in the screenshot).

It is just a proper kill of the app.

What do you think about it?

**Comment by jamal2362** [comment]
I'll think of something. But for now, I'll close here. As soon as I have decided, I will open this issue again.
