### ISSUE TITLE
Current title not shown in Android 13

### ISSUE THREAD

**Issue by eengnr** [jamal2362/URL-Radio#18]
The title of the current song is not shown in the Android 13 media controls (using v9.1)
Transistor however (v4.1.1) shows the title for the same stream. Is this an intentional difference?

**Comment by jamal2362** [comment]
You must mean in the notification bar?

I can confirm this.
This came from the switch from Exoplayer to Media3.

I will take a look at this.

**Comment by jamal2362** [comment]
https://github.com/jamal2362/URL-Radio/commit/ed102e06876e52c1fbc51094244d5d321890cfbd
