### ISSUE TITLE
Home screen station shortcuts say "App isn't installed"

### ISSUE THREAD

**Issue by ximcix** [jamal2362/URL-Radio#19]
Station shortcuts placed on the home are reporting "App isn't installed" when pressed.
If I open the app and tap the same station the shortcut was created from, the station plays just fine.

![Screenshot_20221221_224304_One UI Home](https://user-images.githubusercontent.com/22955792/209050889-5f1835fd-c097-4966-ab9a-09f54cd3feae.jpg)

**Comment by jamal2362** [comment]
Which launcher is this?

I have no problems here.

**Comment by ximcix** [comment]
I'm using a Samsung Galaxy S21 ultra, with One UI 5.0 launcher.

**Comment by jamal2362** [comment]
Hey 😉

I tried it on my Samsung Galaxy Tab S8+ with OneUI 5.0 and Android 13 and see no problem here. 
The shortcuts can be launched without any problems.

If the problem persists, I recommend installing the latest version from GitHub.
If necessary, you can also reinstall the app.
Make a backup of the stations before.


https://user-images.githubusercontent.com/15986930/222369190-6ff0f0ba-59da-43a9-80ae-06127179fc3d.mp4
