### ISSUE TITLE
Not on F-Droid?

### ISSUE THREAD

**Issue by Senor-S** [jamal2362/URL-Radio#20]
I can't find URL Radio on F-Droid nor Izzy on Droid repo. Is this intentional or haven't you been discovered yet?

Thank you for this great app!

**Comment by Poussinou** [comment]
The app is available on IzzyOnDroid [here](https://apt.izzysoft.de/fdroid/index/apk/com.jamal2367.urlradio). Try to refresh your repo in your F-Droid app.

**Comment by Senor-S** [comment]
Yeah, I'm an idiot. Izzy was deselected somehow and I didn't check that first. Cheers!
