### ISSUE TITLE
Latest update from PlayStore does not show title in my car via bleuthooth

### ISSUE THREAD

**Issue by psylion** [jamal2362/URL-Radio#25]
I recently receive an update from the playstore. After this, the title of the track and station are not displayed anymore in my car.
It was perfectly displayed in the previous version.

**Comment by psylion** [comment]
In addition, the widget on lock screen does not update neither.

**Comment by jamal2362** [comment]
Hey,

What if you install the last app here from Github instead of Google Play Store ?

**Comment by psylion** [comment]
Will try that tomorrow...
A bit late  right now
Rhx for the advice

Will let you know

**Comment by jamal2362** [comment]
Can you try this test apk?
https://files.fm/f/azf33csvs

Please let me know.

**Comment by psylion** [comment]
This is the same version
Version 9.1 ("All New")
After install i got message :
App not installed conflicts with existing package.
Do I need to uninstall first?

**Comment by jamal2362** [comment]
Yes you need to uninstall it first.
Make a backup in the settings of the stations before.

**Comment by psylion** [comment]
Great,
Uninstall after export and install apk provided
Works great, restore stations and now the display is working fine
Thanks for the tip

**Comment by jamal2362** [comment]
No Problem. :)
A new release is on the way soon.
Take a look in the GitHub Release for a new version.

Google Play Store support will be drop soon because of the strict guidelines.

**Comment by psylion** [comment]
Awesome, thanks!

**Comment by jamal2362** [comment]
URL Radio 9.2 is now available!
