### ISSUE TITLE
Radio stop buffering when connectivity is lost

### ISSUE THREAD

**Issue by moxwel** [jamal2362/URL-Radio#27]
For context...

I always use the subway. Sometimes, the connectivity there is poor and cellular data is lost.

Obviously, the radio stops playing for a little, and when the connection is restored, the radio plays again. But sometimes it doesn't: the radio stops buffering and no music plays.

When this happen, I need to open the app and select the radio again, then it plays music again.

I have experimented turning off the cellular data for a bit, and radio closes when has passed ~15 secs.

Sometimes when connectivity is intermittent, the radio does not close itself, but stops buffering, there's no music.

Is there a way to prevent this from happening?

Love the app ❤️
Thanks!

> Phone info: Xiaomi Redmi Note 10s
> Android info: Android 12 MIUI 13.0.12
> App info: version 9.1

**Comment by jamal2362** [comment]
Fixed

**Comment by jamal2362** [comment]
URL Radio 9.2 is now available with the fix!
