### ISSUE TITLE
Google Play's "About this app" mentions neither "Open source" nor this github repo.

### ISSUE THREAD

**Issue by jaimet** [jamal2362/URL-Radio#28]
The "About this app" text for [this app on Google Play](https://play.google.com/store/apps/details?id=com.jamal2367.urlradio) ("URL Radio is a radio app that allows you to listen...") does not say that this app is open source, nor does it link to [this github repo](https://github.com/jamal2362/URL-Radio).

Could you please add some text to say both that:
1) this app is open source and that
2) the github repo for the app is [here](https://github.com/jamal2362/URL-Radio)?

(I would submit a PR, but I don't think that the "About this app" text is contained in this repo.)

PS: thank you for writing URL-Radio - transistor is good, but URL-Radio is much better!

**Comment by EBRJR1957** [comment]
What is the difference between the two?

**Comment by jamal2362** [comment]
No changes are currently planned here. If someone wants to know if this app is open source, type URL Radio into Google and notice that it is hosted on GitHub.

**Comment by EBRJR1957** [comment]
Neither I, nor anyone else, cares about its source. I was being too futuristic. 

J'en suis désolé 

Edward B. Reynolds, Jr.| Of Counsel

KELLERHALS FERGUSON KROBLIN PLLC
Royal Palms Professional Building} 
9053 Estate Thomas, Suite 101
St. Thomas, VI 00802
Tel      340.779-2564
Cel      917.386.8969
Fax     888.316-9269
Email   EReynolds.kellfer.com

SOLOMON BUM HEYMANN LLP
(New York office)
40 Wall Street, 35th floor
New York, NY 10005
Tel      212.267.7600
Fax     212.267.2030

www.kellfer.com
www.solblum.com 
DISCLAIMER: The information contained in this e-mail may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, or duplication of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately and delete all copies. 
________________________________

**Comment by jaimet** [comment]
> No changes are currently planned here. If someone wants to know if this app is open source, type URL Radio into Google and notice that it is hosted on GitHub.

**_Once I know that I'm looking for "URL Radio"_**, the fact that's it's open source is obvious. But _**if I don't know that the app that I'm looking for is called "URL Radio"**_ and I go to the Play Store and search for "Open source radio", I'm presented with a list of 29 apps that does **_not_** include "URL Radio". Don't worry though - that's clearly too difficult to understand.

**Comment by EBRJR1957** [comment]
You sound hysterical. 



Edward B. Reynolds, Jr.| Of Counsel

KELLERHALS FERGUSON KROBLIN PLLC
Royal Palms Professional Building} 
9053 Estate Thomas, Suite 101
St. Thomas, VI 00802
Tel      340.779-2564
Cel      917.386.8969
Fax     888.316-9269
Email   EReynolds.kellfer.com

SOLOMON BUM HEYMANN LLP
(New York office)
40 Wall Street, 35th floor
New York, NY 10005
Tel      212.267.7600
Fax     212.267.2030

www.kellfer.com
www.solblum.com 
DISCLAIMER: The information contained in this e-mail may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, or duplication of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately and delete all copies. 
________________________________
