### ISSUE TITLE
Labels, File (m3u, etc, and Ware OS 

### ISSUE THREAD

**Issue by EBRJR1957** [jamal2362/URL-Radio#29]
This is great. I actually found it because I was looking for a way to play my paid subscription music on my Samsung Watch Pro 5. At this point, "wearables" may be ready for prime time particularly, for me, untethered from a smartphone. I neither understand nor use the social media concept of "play list" so even the major services (Deezer, YouTube etc) that had are useless. Also, I have my own personal server that is available all the time. While I am sure you didn't intend this for wear OS, it works perfectly other than the UI which, of course, is designed for a smartphone. In fact, I like it so much that I AM using it on my smartphone now! 2 issues: (a) is there a way to import from a streaming play list file (i.e., m3u, pls, etc)?, and, (b) the label tagging/picture function worked for a while, then quit. Is that function dépendant on how the stream is imported and/or the music provider?

Thanks

Ef

**Comment by jamal2362** [comment]
No planning atm. 
Sorry.

**Comment by EBRJR1957** [comment]
Don't be sorry. It's OK 

Edward B. Reynolds, Jr.| Of Counsel

KELLERHALS FERGUSON KROBLIN PLLC
Royal Palms Professional Building} 
9053 Estate Thomas, Suite 101
St. Thomas, VI 00802
Tel      340.779-2564
Cel      917.386.8969
Fax     888.316-9269
Email   EReynolds.kellfer.com

SOLOMON BUM HEYMANN LLP
(New York office)
40 Wall Street, 35th floor
New York, NY 10005
Tel      212.267.7600
Fax     212.267.2030

www.kellfer.com
www.solblum.com 
DISCLAIMER: The information contained in this e-mail may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, or duplication of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately and delete all copies. 
________________________________

**Comment by EBRJR1957** [comment]
You are overly concerned 

Edward B. Reynolds, Jr.| Of Counsel

KELLERHALS FERGUSON KROBLIN PLLC
Royal Palms Professional Building} 
9053 Estate Thomas, Suite 101
St. Thomas, VI 00802
Tel      340.779-2564
Cel      917.386.8969
Fax     888.316-9269
Email   EReynolds.kellfer.com

SOLOMON BUM HEYMANN LLP
(New York office)
40 Wall Street, 35th floor
New York, NY 10005
Tel      212.267.7600
Fax     212.267.2030

www.kellfer.com
www.solblum.com 
DISCLAIMER: The information contained in this e-mail may be privileged, confidential, and protected from disclosure. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, or duplication of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately and delete all copies. 
________________________________
