### ISSUE TITLE
Background color of the Player

### ISSUE THREAD

**Issue by xmha97** [jamal2362/URL-Radio#30]
Hi, the theme is light.

Why the bottom on the app (player) dark?

![Screenshot_2023-03-03-02-19-03-694_com.jamal2367.urlradio.jpg](https://user-images.githubusercontent.com/23485114/222578025-1b63ea6b-79cd-409b-8837-ecffa7aba3db.jpg)

**Comment by jamal2362** [comment]
Hey!

This is normal. It's not an issue.
The bottom sheet is always dark, the rest is light as you can see.

These are design decisions that I made that way.

**Comment by xmha97** [comment]
Ok, you can add theme manager.

![Screenshot_2023-03-03-02-45-20-663_dev.lucanlm.antimine.jpg](https://user-images.githubusercontent.com/23485114/222584296-391ae9af-5cb8-484f-b8f6-01c34f673452.jpg)

If you think it is taking too much time, close this issue.
