### ISSUE TITLE
[Feature Request] Folders

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/URL-Radio#32]
We should be able to create a folder and add different radio stations in it. Displaying all radio stations in one list causes confusion.

**Comment by jamal2362** [comment]
This is not currently planned.

It is automatically sorted from 0-9 and A-Z.
If you want to have a radio station on top then set it to favorite by swiping this station.

URL Radio is designed to have it as simple as possible. It should look manageable and clean.

**Comment by bakinazik** [comment]
If that's not what you want, you can add a search button to avoid confusion.

**Comment by bakinazik** [comment]
now i can't even create folders or search the stations. which makes me feel like i'm stuck in the interface..
