### ISSUE TITLE
[Bug Report] Notification Issue

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/URL-Radio#33]
When I play a station and switch to another station, the picture of the previous station is stuck in the notification.

**Comment by bakinazik** [comment]
https://user-images.githubusercontent.com/64368231/222971180-127a3c8a-3ad4-4fe5-85ac-064694f9fd6e.mp4

**Comment by jamal2362** [comment]
Hey 🙂

I cannot reproduce this.
I'll leave this issue open in case I get it too.
I have tested it from Android 5 to Android 13 and do not have this issue.

**Comment by bakinazik** [comment]
Android 12, MIUI 13.0.3, Poco F2 Pro

**Comment by jamal2362** [comment]
Does the problem still exist ?

Don't have the Issue on me so far. 
After a few days of testing...

Have you tried to disabled battery optimization for the app ?

**Comment by bakinazik** [comment]
transistor app have this issue too.
and yeah i tried the give all permission but still same issue.

**Comment by jamal2362** [comment]
I'm closing here.
Please check your OS for issues.
