### ISSUE TITLE
Android Auto shows no title and station images

### ISSUE THREAD

**Issue by ghost** [jamal2362/URL-Radio#35]
Hi.
App not fully compatible with Android auto. Like the last version of Transistor.
See ticket i posted on github for this App.

**Comment by jamal2362** [comment]
Hey 🙂

Yes this is currently a problem.
Everything seems to work except the title and station images.

**Comment by ghost** [comment]
That's it 😊

**Comment by jamal2362** [comment]
It should now work in the next release.
