### ISSUE TITLE
Add this app to fdroid

### ISSUE THREAD

**Issue by CodeCubeNeo** [jamal2362/URL-Radio#4]

**Comment by ksaerdna** [comment]
Program can be installed via F-Droid client after having added Izzy's repository: https://apt.izzysoft.de/fdroid/

**Comment by jamal2362** [comment]
It's available on Izzy´s Repo.

That's why I'm closing here now.

**Comment by serrq** [comment]
Might you add your app to F-droid official repo also?

**Comment by DJCrashdummy** [comment]
IMHO this should be reopened as it is still not added to the fdroid-repo and hence unfortunately harder to discover for users.

**Comment by ikanakova** [comment]
+1 F-Droid official repo would be really cool!
