### ISSUE TITLE
An option to disable swipe feature

### ISSUE THREAD

**Issue by xmha97** [jamal2362/URL-Radio#41]
Thanks for adding swipe feature.
Please add an option to disable swipe feature.

![Screenshot_2023-03-30-23-30-36-861_com.jamal2367.urlradio.jpg](https://user-images.githubusercontent.com/23485114/228951190-714bcbd8-65ac-48a5-bd70-83b109082c90.jpg)

**Comment by jamal2362** [comment]
The app has a very minimal structure.
If the swipe function is deactivated, you can no longer delete stations and set them as favorites.

That's why I'm closing here.

**Comment by xmha97** [comment]
You can add delete but on edit mode.

![Screenshot_2023-03-31-05-56-30-610_com.jamal2367.urlradio.jpg](https://user-images.githubusercontent.com/23485114/229007255-016e961d-2559-4e82-ad0f-65a697a32966.jpg)
