### ISSUE TITLE
Sync with M3U link

### ISSUE THREAD

**Issue by xmha97** [jamal2362/URL-Radio#42]
Hi,
I adding my stations here:
https://raw.githubusercontent.com/xmha97/livestream/master/list.m3u
Now I want to sync it with the "URL Radio" app.
Please add this feature.
Thanks.

I can do it on Kodi:

![image](https://user-images.githubusercontent.com/23485114/229339999-2e51f4e1-9cb6-438d-9295-8996266ebc59.png)

**Comment by xmha97** [comment]
On Android, I using this app:

![Screenshot_2023-04-03-05-20-42-324_com.m3u.app.jpg](https://user-images.githubusercontent.com/23485114/229393942-3d81ab1c-4cec-436c-9359-3a97b6193ba5.jpg)

**Comment by jamal2362** [comment]
Hello!

This is not planned for the future, because too few would use it.

Thanks for the request anyway.

Here is the issue for now.
