### ISSUE TITLE
[Feature request] Floating button

### ISSUE THREAD

**Issue by SIRSteiner** [jamal2362/URL-Radio#43]
I think floating buttons for settings and adding station would be better than at the bottom.

Thank you!

**Comment by jamal2362** [comment]
Look here:
https://github.com/jamal2362/URL-Radio/blob/master/app/src/main/res/layout/card_add_new_station.xml

It's already present.
I close this Issue.

**Comment by SIRSteiner** [comment]
Okay, I will wait until the next release because in v10.1 it is not present.

**Comment by jamal2362** [comment]
You don't need to wait. It is already available since version 9.2.

**Comment by SIRSteiner** [comment]
Look theses buttons are not floating. v10.1 F-Droid
![IMG_20230403_065743](https://user-images.githubusercontent.com/3488638/229415385-41a3fe7d-02f1-4e4f-9050-3de4bed56633.jpg)
