### ISSUE TITLE
[Feature request] Buttons at lock screen

### ISSUE THREAD

**Issue by DerSaxxe** [jamal2362/URL-Radio#44]
Please add buttons for previous and next station at the lock screen.

Thank you

**Comment by jamal2362** [comment]
![Screenshot_20230403-073234](https://user-images.githubusercontent.com/15986930/229419752-8f62283f-0100-44b3-b5b7-8b96142434df.png)

**Comment by DerSaxxe** [comment]
Okay, please change this issue to bug, sorry

**Comment by DerSaxxe** [comment]
![IMG_20230403_073607](https://user-images.githubusercontent.com/3488638/229420606-8a8420d5-ec13-46b4-b22a-63339347c772.jpg)

**Comment by DerSaxxe** [comment]
I opened a new issue for that problem.
