### ISSUE TITLE
Start stream via intent/tasker

### ISSUE THREAD

**Issue by AndiLeni** [jamal2362/URL-Radio#5]
Hello,

I want to ask, wether it is possible to start a stream with the automation app tasker or with an intent. 
I'd like to automatically play a stream when my phone connects to my car.

Thanks and kind regards

**Comment by jamal2362** [comment]
Such a function is not planned.
Therefore I close here.

**Comment by rodrigoswz** [comment]
Any chance to reopen it? It would be very useful for automations
