### ISSUE TITLE
URL Radio on Amazon Firestick/FireTV

### ISSUE THREAD

**Issue by ximcix** [jamal2362/URL-Radio#5]
I recently discovered your app and it has since replaced another app that I used for a few years to play web streams.
I love the clean interface and the simplicity of the app.
I have it installed on my phone, my Android TV box and my Amazon Fire Stick/TV.

My only issue so far is I can't navigate to the "Add New Station" button using the 4-way directional pad on the Fire TV remote (not a touch screen device).
I can move to the settings gear and access that page, but even when I return to the main screen, I can't highlight the "Add New Start" button.
I hope this is an easy fix.

Regards,

Marlon.

**Comment by jamal2362** [comment]
Hello,

This app is not designed for Android TV / Fire TV.
This needs a lot of work, I do this as a hobby so unfortunately I have to reject it.

Greetings
Jamal

**Comment by ximcix** [comment]
no worries.
Thanks for responding

**Comment by jamal2362** [comment]
As a workaround:
Use a mouse.

Even if you can click on "Add new Station" with the remote control, you can't add favorites or delete stations.
You can only do that by touch or with a mouse.
