### ISSUE TITLE
 proposal- tab "favorite songs"

### ISSUE THREAD

**Issue by phyrz91** [jamal2362/URL-Radio#51]
Would it be possible to add a "favorites songs" tab?

I often listen to different stations and there are a lot of interesting songs whose titles are hard to remember. Adding titles to the "favorite songs" tab could be solved by adding, for example, a heart next to the currently playing section.

Ps. Can you move the title copy button more to the center, or alternate it with a timer? Or add such an option in options? Nowadays it is often difficult to click the ob button. Thx.

**Comment by jamal2362** [comment]
Hello,
this does not fit the guidelines I follow.
Therefore I close here.
