### ISSUE TITLE
Stream Guys link not working

### ISSUE THREAD

**Issue by MiracoleWorker** [jamal2362/URL-Radio#53]
Hello, I would like to listen to 91.5 WSCR Sandwich Community Radio. However, their [Stream Guys Link](https://player.streamguys.com/wscr/sgplayer/player.php) produces an error message that says "The station is not valid." The only two listening links on their website are either Stream Guys or TuneIn Radio. Do you have an idea why URL Radio won't accept this link?

**Comment by jamal2362** [comment]
Hey,

you cannot use a Website as link.

Please use another url ends with .mp3, .aac etc.
