### ISSUE TITLE
[Feature Request/Suggestion] Grid View

### ISSUE THREAD

**Issue by Eiion** [jamal2362/URL-Radio#54]
Currently we have a List view for the stations which we have added to the app and it looks something like this:
![Screenshot_2023-05-31-13-40-23-133_com-jamal2367-urlradio](https://github.com/jamal2362/URL-Radio/assets/18130829/9dff319a-c313-4f84-978d-c07272bd6b8f)
And with more than just 8 stations we need to scroll. While this is a workable solution it's not really user-friendly - well, at least to me it's not the best way to deal with having multiple stations added.
So here's my suggestion to add a "Grid View" option for the stations. Which could looks something like this:
![Screenshot_2023-05-31-13-33-13-273_de-danoeh-antennapod](https://github.com/jamal2362/URL-Radio/assets/18130829/a56d961b-c553-478a-a43c-91d84008cd05)
I took the screenshot from AntennaPod (a podcast listening app). There we can even adjust the amount of tiles in a row pinching/widening with a two finger input.

While adjustable tile size wouldn't be necessary right away, four tiles per row would be a great start for a quality of life update.
Considering the stations typically have their names right there in the logo, this would also be sufficient to keep them apart from one another.

I hope this could be added to the options in the near future or at least be considered as a down the line update. Thanks.

**Comment by jamal2362** [comment]
A GridView version will not come because the radio has this unique design.

**Comment by Eiion** [comment]
Uhm, ok. So a user tells you the "design" isn't very practical and makes a suggestion - and completely disregard if by calling this most basic list layout "unique". Okay then.
Feels like it would be more honest had you replied with "No, I don't want to."
