### ISSUE TITLE
[Feature Request] Add retro mode

### ISSUE THREAD

**Issue by heshamgamal410** [jamal2362/URL-Radio#55]
![Screenshot from 2023-06-13 01-21-37](https://github.com/jamal2362/URL-Radio/assets/91227805/64e72577-4084-42b2-b2a9-b4d93797fbd6)
It would be great if you can implement something similar to this screenshot (It's the mini player view from the linux app Shortwave), But in the form of a full screen mode with the channel and track name.

**Comment by jamal2362** [comment]
Hello,
this does not fit the guidelines I follow.
Therefore I close here.
