### ISSUE TITLE
[Feature suggestion] Auto play on Bluetooth 

### ISSUE THREAD

**Issue by srt54558** [jamal2362/URL-Radio#56]
Hi! My phone always automatically connects to my car over Bluetooth when I turn the car on, and i always have to open the app and select the radio. 

Can you maybe somehow implement that if a saved target Bluetooth device gets connected, the player automatically starts the last played radio or a radio that's selected. If not a good feature would be to start the last played radio on app start! And a toggle to disable it in settings for people that do not want this!

I'd be reeeally happy if you'd implement this feature!

Even if not, I love the simple app design and the fast song selection! Thank you!

**Comment by jamal2362** [comment]
Hi!

I don't think this function is useful for a radio.
This makes more sense for music streaming.

Therefore, this issue is closed.
