### ISSUE TITLE
[feature suggestion] Look for updates

### ISSUE THREAD

**Issue by srt54558** [jamal2362/URL-Radio#57]
Hi! 
I think this app needs an automatic update search on app start if it's not downloaded from f-droid. Some people (including me) download apps simply on GitHub, and if a update is found, it just redirects me. I just think of a simple function running once every time the app is started and it just looks for a new GitHub release and redirects to the release page

**Comment by jamal2362** [comment]
Hello,

this function is already implemented.
Install the version 10.3 as a test and start the app then you will see a new version and it will also be redirected directly to GitHub.
