### ISSUE TITLE
Add "Edit Favorite / Delete" option in settings

### ISSUE THREAD

**Issue by u2fly** [jamal2362/URL-Radio#60]
Add "Edit Favorite / Delete" option in the settings screen to be able to enable/disable station drag gesture.

**Comment by jamal2362** [comment]
Hello,
after long consideration I have decided against it.
This is not planned for the time being.
Since it restricts functions too much.

**Comment by u2fly** [comment]
> Since it restricts functions too much.

It does not restricts, but prevents mistakenly delete station by slide gesture.

Why there is no confirmation dialog before delete station?

**Comment by jamal2362** [comment]
Hello,

nothing is deleted just like that.
If you delete a station, you will be asked beforehand.

![Screenshot_20230712-211716](https://github.com/jamal2362/URL-Radio/assets/15986930/71b36182-a295-4c77-b545-159b75755b23)

**Comment by u2fly** [comment]
Main reason of adding "Edit Favorite / Delete"  disable option in preferences is just to be able temporary disable horizontal slide gestures.

It does not restrict anything, but gives user more control on app behavior.

**Comment by jamal2362** [comment]
This is a feature that aims exactly to use it.
It offers the user the possibility to delete or favorite a station.

Disabling this feature makes no sense to me. Even if you could disable this in the settings...

The swipe function was not built in for nothing by the original author @y20k 
(Original Author of this fork)

I'm still thinking about adding it, but it's not the priority now.

**Comment by jamal2362** [comment]
I have thought about it again and have come to the conclusion that this feature will not be implemented.

Therefore I close here.
