### ISSUE TITLE
Cannot play stream from enigma2 openwebif

### ISSUE THREAD

**Issue by mjray** [jamal2362/URL-Radio#61]
I can add the stream URL to the app by sharing the m3u file from a browser. The stream URL looks like http://192.168.0.5:8001/1:0:1:23C3:446:1:C00000:0:0:0 which is correct but I can't edit and save the URL. Attempting to add it directly results in a "Station is not valid." message.

Clicking play starts the button animation, nothing plays and eventually it stops.
I expected it to play.

According to ffplay, the stream structure is:

Input #0, mpegts, from 'http://192.168.0.5:8001/1:0:1:23C3:446:1:C00000:0:0:0':
  Duration: N/A, start: 68519.046933, bitrate: 256 kb/s
  Program 9140 
  Program 9142 
  Program 9143 
  Program 9144 
  Program 9153 
  Program 9154 
  Program 9155 
    Stream #0:0[0x76f](fra): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 256 kb/s
  Program 9156 
  Program 9157 
  Program 9158 
  Program 9159 
  Program 9163 
  Program 9164 
  Program 9165 
  Program 9166 
  Program 9168 
  Program 9175 
  Program 9176 
  Program 9177 
  Program 9178 
  Program 9179 
  Program 9180 
  Program 9181 
  Program 9182 
  Program 9183 
  Program 9184 
  Program 9185 
  Program 9186 
  Program 9187 
  Program 9194 
  Program 9198 
  Program 17020 
  Program 17021 
  Program 17022 
  Program 17024 
  Program 17026 
  Program 17030 
  Program 17031 
  Program 17035 
  Program 17036 
  Program 17054 
  Program 17099 

Is it possible to play such streams? They play in vlc or mpv but of course they're not specific radio players like URL-Radio.

It is also possible to get an aac stream from the box but then it also has a blank video stream. That looks like this in ffplay:

Input #0, mpegts, from 'http://192.168.0.5:8001/1:0:1:23C3:446:1:C00000:0:0:0?bitrate=32000':
  Duration: N/A, start: 69401.969667, bitrate: 124 kb/s
  Program 1 
    Stream #0:0[0x66]: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1[0x67]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 124 kb/s

I think this is the related error in adb logcat:
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal: Playback error
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:   l1.n: Source error
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at l1.r0.k(SourceFile:17)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at l1.r0.handleMessage(SourceFile:354)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:   Caused by: c2.d: None of the available extractors (b, b, d, j, l, a, b0, e, g0, e, f, a, d, d, b, a) could read the stream.
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at h4.t.O(SourceFile:184)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at r1.j0.a(SourceFile:120)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at v1.k.run(SourceFile:41)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-04 11:55:44.531 11086 12811 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:923)

Let me know if I can offer any more info. Thanks for reading this far!

**Comment by jamal2362** [comment]
Hey,

This is not a valid streaming url...

What works on an Enigma2 receiver does not mean it will work here.

**Comment by mjray** [comment]
> This is not a valid streaming url...

What do you regard as valid streaming URL? It works if put into the stream entry box in the other apps I mentioned.



> What works on an Enigma2 receiver does not mean it will work here.

The stream is being transcoded and sent by an Enigma2 (at the IP address 192.168.0.5), not played on it.
