### ISSUE TITLE
Possible typo in app settings: "Export Station"

### ISSUE THREAD

**Issue by matchboxbananasynergy** [jamal2362/URL-Radio#62]
In the app's settings, under "Import & Export", there is an "Export Station" option. Based on context, as well as the other settings, I believe the correct phrasing there would be "Export Stations", since the setting's description talks about the "entire collection of radio stations".

**Comment by jamal2362** [comment]
Hey!

Thank you for the report!

My main language is German.
I must not have discovered it since the language is set to German. 😃

The typo is fixed.
https://github.com/jamal2362/URL-Radio/commit/59ce1810b6c6032eb3960d64f1c200d3ec7a8386
