### ISSUE TITLE
Add streaming audio quality "kbps" alongside the stations 

### ISSUE THREAD

**Issue by demarkz** [jamal2362/URL-Radio#63]
Hi, 
You could add the radio streaming quality next to the radio station in the search box and now playing, something like > Radio AAA - 128 kbps or Radio BBB - 320 kbps. Sometimes I wanna know the transmission quality and I can't find it anywhere.

**Comment by jamal2362** [comment]
Hello,

thanks for the feature request.
I have just started the implementation.

I am even thinking about going further.
Besides the bitrate it would be good if the codec would be displayed.

As soon as this is ready I will write here again.

**Comment by jamal2362** [comment]
Function was implemented.

![Screenshot_20230712_175032](https://github.com/jamal2362/URL-Radio/assets/15986930/c7e2704b-cc9f-433d-82e1-e1e26a624221)

**Comment by demarkz** [comment]
Thanks a lot. It's much better now. I think you should put this option in the now playing screen for radios already saved in the favorites next to the radio url as well. 

![Screenshot_20230713-011856_URL Radio](https://github.com/jamal2362/URL-Radio/assets/16445902/aa392a5a-1949-4723-90fe-1535fecca72c)

**Comment by jamal2362** [comment]
Hello,

There are many stations that display 0kbps, which is incorrectly captured by the radio-browser.info API.

Since it is only displayed in the search for some stations, this is acceptable.

**Comment by jamal2362** [comment]
Hey @demarkz ,

so I added it.
But this is only displayed if it was retrieved from the radio-browser.info API.
Otherwise there is nothing there.

![Screenshot_20230713_155258](https://github.com/jamal2362/URL-Radio/assets/15986930/f41aaa33-a4fd-44d2-a4e9-836ef0fb2c47)

**Comment by demarkz** [comment]
Yeah! Great! It helps a lot to search and listen to radios with high quality broadcasting. Thank you so much for adding this option since I love audio high quality.
