### ISSUE TITLE
[Feature request] Option to display the previous font

### ISSUE THREAD

**Issue by Go-rom** [jamal2362/URL-Radio#64]
Hello @jamal2362 

IMHO the app looked prettier with the previous font, would it be possible to reintroduce this font in an optional way please ?

Thank you for this great app
Best regards

**Comment by jamal2362** [comment]
Hello,

currently there are no plans to add a font.

Maybe again in later future but currently not.

Greetings,
Jamal

**Comment by Go-rom** [comment]
No problem, thank you for your answer 👍🏻
