### ISSUE TITLE
[enhancement] Pre-play Option

### ISSUE THREAD

**Issue by itsmartashub** [jamal2362/URL-Radio#66]
### Describe the feature
- Pre-play Option for New Stations and URL Edit

The feature would involve the ability to play a station before adding it to the playlist.

### Why would this be useful to add?
This would save time and provide a convenient way to quickly preview stations before adding them to the playlist.
With the proposed enhancement, it would be handy to have an option to play the station right from the search results, without the need to first add it to the playlist.

The search entry may include stations that are not aligned with the desired criteria, and one may not realize this until the station is already added to their playlist and played. Incorporating a pre-play option when the list is rendered on the search query could help prevent this.

**Comment by jamal2362** [comment]
Hey,
It should now be implemented in the URL Radio 11.1.

Simply click on a station and the preview will start. :)

![Screenshot_20230715-161601](https://github.com/jamal2362/URL-Radio/assets/15986930/ea1f6c42-e67b-455d-ba1b-fbe8eae8ed46)
