### ISSUE TITLE
[Feature Request] On manual URLs, populate metadata from icy-* headers

### ISSUE THREAD

**Issue by jprjr** [jamal2362/URL-Radio#69]
Hi there - I have a private Icecast stream running that I'd like to add to the app, and still display a name, description, etc.

It would be great if, when using a custom URL, the app could parse the various `icy-` headers and use that to populate the title, bitrate etc, so it displays in the radio station list with the title rather than the URL without the need to edit.

**Comment by jamal2362** [comment]
Hi,

This does not sound bad. 
Can you paste me your stream link to test here ?

**Comment by jamal2362** [comment]
https://github.com/jamal2362/URL-Radio/commit/9c4ae7a04dff184197109cf5fb64dee90fdabf9a
