### ISSUE TITLE
[Feature Request] More intuitive stream editing

### ISSUE THREAD

**Issue by jprjr** [jamal2362/URL-Radio#70]
I added a stream URL and long-pressed on it to edit. Since the name was set to the URL value, and the editor doesn't label the field - I thought I was editing the URL of the stream, not the name, and got frustrated with trying to figure out how to set a custom name.

It wasn't until I long-pressed on a stream that I added via search that I realized the field is actually the name.

Placing a label next to the field in the edit view to make it clear you're editing the stream name and not the stream URL would be a huge help, thank you!

**Comment by jamal2362** [comment]
Check the settings to see if the two boxes are checked to edit the stream name and stream addresses.

It's very easy, just long press on the station image to start the edit mode.

I see no need to change anything here, so I'll close here.
