### ISSUE TITLE
Add ability to set custom thumbnail 

### ISSUE THREAD

**Issue by ThatOneCalculator** [jamal2362/URL-Radio#71]
Some stations may not broadcast a thumbnail, but the ability to manually set a thumbnail would be nice instead of only having the default icon. 

![Screenshot_20230820-101824.png](https://github.com/jamal2362/URL-Radio/assets/44733677/be2be249-09dc-4dd2-bbe4-88cb62573a04)

**Comment by jamal2362** [comment]
Hey, 

please hold long on the station name or the standard thumbnail to open the edit mode.
Then you can set a custom Image.

**Comment by ThatOneCalculator** [comment]
Oh, thank you!
