### ISSUE TITLE
sleep timer resets if connection lost, then playback continues indefinitely when connection resumes

### ISSUE THREAD

**Issue by rulnick** [jamal2362/URL-Radio#72]
On current (11.9) and previous (11.8) versions, sleep/shutoff timer loses effect if the connection drops even briefly. The result is that playback eventually resumes and then continues indefinitely.

**Comment by jamal2362** [comment]
Fixed:
https://github.com/jamal2362/URL-Radio/commit/f0c4069ce7ba45b333cb400e8b49130d60a6d4d7
