### ISSUE TITLE
Unable to play BBC Radio 3 and import backup 

### ISSUE THREAD

**Issue by arrigoG** [jamal2362/URL-Radio#73]
Hello,

I'm unable to add BBC Radio 3 stream and play some music. I can add the stream url but this is always silent. In Transistor the link works perfectly but not here.

I also tried to import a backup but when I select the folder where it is stored any of the files are available. Can you please help? 

Many thanks

**Comment by jamal2362** [comment]
Fixed:
- [Problem solved that HLS (M3U8) streams could not be played back correctly](https://github.com/jamal2362/URL-Radio/commit/a7ef983db5466718fc3bef3399c7a5017e9e2c1e)

**Comment by arrigoG** [comment]
Thanks now it works however when I try to add another BBC Radio channel for some reasons this doesn't play and stay stored in the list. This issue doesn't happen into Transistor. I can't explain why this happens in your app.
I hope you could fix it one day. Thank you for all the great work.

**Comment by dochego** [comment]
With v12.0 the BBC HLS streams work fine again for me, thanks for the fix. 
@arrigoG I can add different BBC channels to the station list without problem.

**Comment by arrigoG** [comment]
I have just tried again I believe I have selected the wrong source of the stations (some have the red icons, some the new BBC logo, some HD quality are not playing).
Some links probably are not working properly because they stuck the app and cause a crash.
In Transistor HLS streams are marked as experimental so perhaps they are not 100% compatible.
Well, better than nothing!
