### ISSUE TITLE
Can preview but not add station

### ISSUE THREAD

**Issue by Senor-S** [jamal2362/URL-Radio#74]
Hey, thanks for this awesome app! When I try to add "Die Maus"-station (search for "Maus"), I can play both links in preview-mode. But if I add it, it is visible until i click it, then it disappears and a different station from my list plays.

**Comment by jamal2362** [comment]
Hallo,

da "Die Maus" wohl ein Deutsches Ding ist, schreibe ich hier mal ausnahmsweise in Deutsch.

Ich kann diesen Sender ohne Probleme hinzufügen.

Ich habe ein Tipp für dich.

Mache ein Backup der Stationen in den Einstellungen und Installiere die App neu und Importiere die Sender dann in den Einstellungen wieder.

Vielleicht hat sich da was aufgehangen.

Wie auf dem Bild zu sehen, kann ich den Sender ohne Probleme hinzufügen und auch abspielen.

Was auch noch gut wäre ist zu wissen welche Android Version du nutzt und welches Gerät.

![Screenshot_20230908-185056](https://github.com/jamal2362/URL-Radio/assets/15986930/dd430935-5321-4758-8c30-f77b4f76e473)

**Comment by Senor-S** [comment]
Ich bin ein idiot, hab echt seit Wochen Probleme damit. Jetzt gerade mal Cache geleert und die App beendet und jetzt gehts auch wieder. Kannst also löschen. Danke! :)

**Comment by jamal2362** [comment]
Es gab viele App Updates wie du vermutlich mitbekommen hast.
Da kann es schonmal zu Problemen kommen.

Bevor ich etwas Release dann teste ich alles genau durch.
Man darf auch nicht vergessen das das Android System manchmal echt komisch sein kann. 😃

Ich mache dann mal zu :)
