### ISSUE TITLE
Add sleep timer

### ISSUE THREAD

**Issue by AluminYu** [jamal2362/URL-Radio#77]
Hi! Well, title says it all, it'd be really cool if you added a sleep timer in the app to automatically stop the radio after a certain time :)

**Comment by jamal2362** [comment]
Hello,

The sleep timer is already included.
Start a radio Station and you can set a time.

![Screenshot_20231008-145505](https://github.com/jamal2362/URL-Radio/assets/15986930/b2191d0c-9539-44d4-9e50-23f59a35713d)

**Comment by AluminYu** [comment]
> Hello,
> 
> The sleep timer is already included. Start a radio Station and you can set a time.
> 
> ![Screenshot_20231008-145505](https://user-images.githubusercontent.com/15986930/273449891-b2191d0c-9539-44d4-9e50-23f59a35713d.png)

Oh, I'm really sorry! It seems the timer clock wasn't appearing for some reason when I started playing a station, but I stopped the app and cleared the cache and now I can see it. Thank you for the quick reply my man
