### ISSUE TITLE
❔[Question]: GitHub Releases

### ISSUE THREAD

**Issue by DarkCrypt** [jamal2362/URL-Radio#79]
There's a tag for v12.8 but doesn't appear on releases page?

**Comment by jamal2362** [comment]
https://github.com/jamal2362/URL-Radio/releases/tag/12.8

There you can find the .apk

**Comment by DarkCrypt** [comment]
Thanks friend but I know this and I've already updated the app. I use Obtainium to update apps and it doesn't recognize v12.8 since it's not on the releases page.

Was just wondering why. A GitHub bug?

**Comment by jamal2362** [comment]
It could be a GitHub bug, I can find it normally as I said in the releases overview.

I also just tested the updater in the URL Radio app, it also finds the latest release without any problems.

**Comment by DarkCrypt** [comment]
Ok, sure sounds like a GitHub bug. Thank you for your quick reply. God bless!

Closing.

**Comment by DarkCrypt** [comment]
I found a few old comments from GitHub staff about this bug.

> On occasion, this can happen when the index used to populate the release page goes out of sync with the database holding release records.

> As an interim workaround, you can try editing the release and clicking on Update release without making any changes. This should force a re-sync, causing the missing releases to re-appear.

Sounds like an easy fix if it works.

**Comment by jamal2362** [comment]
Hi,
So I have done it.
Maybe it will work now :)

**Comment by DarkCrypt** [comment]
It worked! All releases showing on GitHub releases page including v12.8. Now we know what's going on.

Thank you for helping experiment. 😀
