### ISSUE TITLE
Cannot add additional radio stations

### ISSUE THREAD

**Issue by ksaerdna** [jamal2362/URL-Radio#8]
Tested the program on two devices, one with Android 11 (installed from Izzy F-Droid) and another one with 8.1 (installed from Play Store). No problems with the first one so far, but cannot add stations on my 8.1 device:

- Start app
- Add first radio station
- Start playback
- Add another radio station -> ignored
- Stop playback
- Try to add a second station -> failure
- Reset application, i.e. clear memory via Settings
- Start app
- Add first radio station
- Add another radio station
- Start playback
- Try to add a third station -> failure, i.e. ignored
- Stop playback
- Try to add a third station -> failure, i.e. ignored

**Comment by jamal2362** [comment]
I can not reproduce this from therefore I close here.

Maybe this is fixed when I switched to Media3.
